"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const sky = "Awesome";
const foo1 = () => "Hi";
const winter = () => console.log("zz");
let arr = [1, 2, 3];
let arr2 = [4, 5, 5];
let arr3 = [true];
let arr4 = ["lite"];
let arr5 = [1, 2, 3];
let a6 = ["a", "b"];
let obj1 = { a: "s" };
obj1.a = "100";
let obj3 = { a: 10, b: "sdsd" };
obj3.b = "100";
const v = "Seoul";
